---
- hosts: luftsensor_deploy
  vars:
    repo_dest: /home/administrator/proj/feinstaub-json-mqtt-bridge
    python_venv: /home/administrator/proj/feinstaub-json-mqtt-bridge-ve

  tasks:
  
  - name: update/checkout git repo
    git:
      repo: 'https://github.com/tbs1-bo/feinstaub-json-mqtt-bridge.git'
      dest: '{{ repo_dest }}'
      version: master

  - name: install dependencies from requirements file in repo
    pip:
      requirements: '{{ repo_dest }}/requirements.txt'
      virtualenv: '{{ python_venv }}'
      virtualenv_python: python3
            
  - name: installing daemontools from package manager
    become: yes  # become privileged
    apt:
      name: daemontools

  #- name: add services to daemontools
  #  shell: 'nohup svscan {{ repo_dest }}/service &'
  #  creates: '{{ repo_dest }}/services/json2mqtt/supervise/lock'

  - name: restart service
    # -d (down) -u (up)
    command: 'svc -du {{ repo_dest }}/services/json2mqtt'
    
  # error during installation in ubuntu 16.04
  #- name: installing daemontools-run from package manager
  #  become: yes  # become privileged
  #  apt:
  #    name: daemontools-run
  #
  #- name: add service to daemontools
  #  command: 'update-service -a {{ repo_dest }}/service json2mqtt'
  #  creates: '/etc/service/json2mqtt'

    
