---
- hosts: luftsensor_deploy
  vars:
    repo_dest: /home/administrator/proj/feinstaub-json-mqtt-bridge
    python_venv: '{{ repo_dest }}/venv'

  tasks:

  - name: update/checkout git repo
    git:
      repo: 'https://github.com/tbs1-bo/feinstaub-json-mqtt-bridge.git'
      dest: '{{ repo_dest }}'
      version: master

  - name: install dependencies from requirements file in repo
    pip:
      requirements: '{{ repo_dest }}/requirements.txt'
      virtualenv: '{{ python_venv }}'
      virtualenv_python: python3

  - name: install supervisor package
    become: yes
    apt:
      name: supervisor
    
  - name: copy supervisor configuration file
    become: yes
    copy:
      src: services/supervisor.conf
      dest: /etc/supervisor/conf.d/json2mqtt.conf
    # register: cpres_supervisorconfig

  - name: restart service
    become: yes
    supervisorctl:
      name: json2mqtt
      state: restarted

  - name: generating documentation
    local_action: command make -C sphinx_doc html

  - name: commiting documentation to local repository
    local_action: command git commit --allow-empty --author='Ansible <ansible@exmaple.com>' -m "[autogenerated] ansible generated documentation" docs

